theme: minimal
markdown: kramdown
plugins:
  - jekyll-seo-tag
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
# Add this line if not present
# or ensure you don’t override existing settings
custom_css: "/assets/css/styles.css"

